<?xml version="1.0" encoding="utf-8"?>

<#--${result}-->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:template match="/">
        <html>
        <head>
            <title>Result of evaluation</title>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        </head>
        <body>
        <!--                ${result}-->
        </body>
        </html>
    </xsl:template>
</xsl:stylesheet>